kind: pipeline
type: docker
name: default

workspace:
  base: /go/src/github.com/carldanley/alfred-hue

platform:
  os: linux
  arch: amd64

volumes:
- name: gopath
  temp: {}

steps:
- name: lint-code
  image: golang
  commands:
  - go get -u golang.org/x/lint/golint
  - golint -set_exit_status ./
  volumes:
  - name: gopath
    path: /go

- name: build
  image: golang
  environment:
    CGO_ENABLED: 0
    GOOS: linux
  commands:
  - go build -a -installsuffix cgo -o alfred-hue
  volumes:
  - name: gopath
    path: /go
  when:
    ref:
    - refs/tags/*
  depends_on:
  - lint-code

- name: dockerize
  image: plugins/docker
  settings:
    auto_tag: true
    repo: carldanley/alfred-hue
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
    - refs/tags/*
  depends_on:
  - build

- name: deploy
  image: bitnami/kubectl
  environment:
    KUBE_CONFIG:
      from_secret: kube_config
    KUBECONFIG: /tmp/.kubeconfig
    NAMESPACE: alfred
    DEPLOYMENT_NAME: hue
    CONTAINER_NAME: hue
    IMAGE_NAME: carldanley/alfred-hue
  commands:
  - printenv KUBE_CONFIG | base64 -d > /tmp/.kubeconfig
  - kubectl set image deployment/$DEPLOYMENT_NAME -n $NAMESPACE $CONTAINER_NAME=$IMAGE_NAME:$DRONE_TAG
  when:
    ref:
    - refs/tags/*
  depends_on:
  - dockerize
