apiVersion: v1
kind: Secret
metadata:
  name: hue
  namespace: homelab
  labels:
    app: hue
type: Opaque
data:
  nats-server: "" # update this to base64 nats connection string (nats://username:password@host-or-ip:port)
  hue-user-id: "" # update this to base64 hue bridge user ID (see README.md for more information on obtaining a hue user ID from your bridge)
